version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "5173:5173" # Adjust the port based on your frontend framework (Vite uses 5173)
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
    driver: local
